version: "3"

services:

  dora-api:
    container_name: dora-api
    image: alanmpinder/gitql-api:latest
    ports:
      - "3000:3000"
    environment:
      - GIT_URL=https://github.com/alanapz/gitql-api.git
      - GIT_BRANCH=release
      - HOST_WORKSPACE_ROOT
      - CORS_ORIGIN
    volumes:
      - "gitql-api-data:/gitql-api:rw"
      - "${HOST_WORKSPACE_ROOT}:/workspace:rw"
      - "~/.ssh:/root/.ssh:ro"

  dora-web:
    container_name: dora-web
    image: alanmpinder/dora-web:latest
    ports:
      - "4200:4200"
    environment:
      - GIT_URL=https://github.com/alanapz/dora.git
      - GIT_BRANCH=release
    volumes:
      - "dora-web-data:/dora-web:rw"

volumes:
  gitql-api-data:
    driver: local
  dora-web-data:
    driver: local
